# Generated by Django 3.0.8 on 2021-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_name', models.CharField(max_length=200)),
                ('option_1', models.CharField(max_length=20)),
                ('option_2', models.CharField(max_length=20)),
                ('option_3', models.CharField(max_length=20)),
                ('option_4', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.BigIntegerField()),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('st_name', models.CharField(max_length=20)),
                ('mobile', models.BigIntegerField()),
                ('college', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='media/images')),
                ('signature', models.ImageField(blank=True, upload_to='media/images')),
                ('usn', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'student_data',
            },
        ),
        migrations.CreateModel(
            name='upload_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_amount', models.IntegerField()),
                ('item_desc', models.TextField()),
                ('images', models.ImageField(upload_to='MEDIA_ROOT/images/')),
            ],
            options={
                'db_table': 'upload_doc',
            },
        ),
        migrations.CreateModel(
            name='user_submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_mobile', models.IntegerField()),
                ('answer', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'user_submit',
            },
        ),
    ]
