# Generated by Django 3.0.8 on 2021-05-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineclass', '0002_user_submit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_submit',
            name='date',
        ),
    ]
